#!/usr/bin/env bash
#ARCHIVE="https://odooku.s3.amazonaws.com/heroku-16/runtimes/python-2.7.13.tar.gz"
ARCHIVE="https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz"

if [ ! -f ".heroku/python/bin/python" ]; then
  puts-step "Bootstrapping python"
  mkdir -p .heroku/python
  curl -s $ARCHIVE 2> /dev/null | tar zxv -C .heroku/python &> /dev/null
fi
